math_with_judge:
  resources_servers:
    math_with_judge:
      entrypoint: app.py
      judge_model_server:
        type: responses_api_models
        name: ???
      judge_responses_create_params: {
        input: []
      }
      should_use_judge: false
      domain: math
      verified: false
math_with_judge_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: math_with_judge
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/math_with_judge/data/dapo17k_train.jsonl
        # From YouJiacheng/DAPO-Math-17k-dedup
        gitlab_identifier:
          dataset_name: dapo17k
          version: 0.0.1
          artifact_fpath: dapo17k_train.jsonl
        license: Apache 2.0
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/math_with_judge/data/aime24_validation.jsonl
        gitlab_identifier:
          dataset_name: aime24
          version: 0.0.1
          artifact_fpath: aime24.jsonl
        license: Apache 2.0
