math_advanced_calculations:
  resources_servers:
    math_advanced_calculations:
      entrypoint: app.py
      domain: agent
      verified: false
math_advanced_calculations_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: math_advanced_calculations
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
        - name: train
          type: train
          jsonl_fpath: resources_servers/math_advanced_calculations/data/train.jsonl
          gitlab_identifier:
            dataset_name: math_advanced_calculations
            version: 0.0.1
            artifact_fpath: train.jsonl
          license: Apache 2.0
        - name: example
          type: example
          jsonl_fpath: resources_servers/math_advanced_calculations/data/example.jsonl
