workplace_assistant:
  resources_servers:
    workplace_assistant:
      entrypoint: app.py
      domain: agent
      verified: false
workplace_assistant_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: workplace_assistant
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
        - name: train
          type: train
          jsonl_fpath: resources_servers/workplace_assistant/data/train.jsonl
          gitlab_identifier:
            dataset_name: workplace_assistant
            version: 0.0.4
            artifact_fpath: train.jsonl
          license: Apache 2.0
        - name: validation
          type: validation
          jsonl_fpath: resources_servers/workplace_assistant/data/validation.jsonl
          gitlab_identifier:
            dataset_name: workplace_assistant
            version: 0.0.4
            artifact_fpath: validation.jsonl
          license: Apache 2.0
        - name: example
          type: example
          jsonl_fpath: resources_servers/workplace_assistant/data/example.jsonl
      max_steps: 6